### ISSUE TITLE
NullPointerException possibility during reconnection

### ISSUE THREAD

**Issue by noslowerdna** [sgroschupf/zkclient#25] opened 2014-06-05 21:13 UTC
It appears that a NullPointerException can be thrown if the ZkClient is being used while a state change requiring a reconnection is being processed.

See https://issues.apache.org/jira/browse/KAFKA-824?focusedCommentId=14019284&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-14019284 for example stack traces and a preliminary analysis of the problem.

**Comment by rmetzger** [comment] 2015-04-30 08:04
I'm affected as well by this issue.

**Comment by jzillmann** [comment] 2015-04-30 15:18
I had a look at the code. Think there are only 2 possibilities that such an exception can occur:
- 1) a null zkConnection is passed in
- 2) a retryUntilConnected action wakes up and the client was closed in meantime

I could reproduce the NPE for case 2 and changed the code to throw an clear exception instead of risking unclear follow up exception like the NPE's.

**Closed by jzillmann** 2015-04-30 15:18 UTC

**Comment by rmetzger** [comment] 2015-04-30 15:21
Thank you for fixing this!

**Comment by hachikuji** [comment] 2015-09-24 19:14
@jzillmann One user is still seeing similar NPEs in ZkConnection.java after upgrading to 0.5. The patch appears to address the race condition around ZkClient.close(), but isn't there still a case where reconnect could cause the Zookeeper reference in ZkConnection to be set to null just before retrying in retryUntilConnected? Unless I'm misunderstanding the code (which is definitely possible), it looks like reconnect is called from the zookeeper event thread, so between the time that ZkConnection.close() and the connection is reestablished in ZkConnection.connect(), what prevents the user from seeing a null Zookeeper in ZkConnection? Maybe I'm missing something?
